name: api-cnn
channels:
  - conda-forge
  - defaults
dependencies:
  - flask=2.0.3
  - numpy=1.21.6
  - pip=21.2.4
  - python=3.8.12
  - streamlit=1.10.0
  - pip:
    - https://download.pytorch.org/whl/cpu/torch-1.10.2%2Bcpu-cp38-cp38-linux_x86_64.whl
    - https://download.pytorch.org/whl/cpu/torchaudio-0.10.2%2Bcpu-cp38-cp38-linux_x86_64.whl
    - https://download.pytorch.org/whl/cpu/torchvision-0.11.3%2Bcpu-cp38-cp38-linux_x86_64.whl